# Generated by Django 5.2.1 on 2025-05-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_component_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/', verbose_name='Изображение'),
        ),
    ]
