# Generated by Django 5.2 on 2025-05-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component', verbose_name='Комплектующее')),
            ],
            options={
                'verbose_name': 'Элемент операции',
                'verbose_name_plural': 'Элементы операции',
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Выдача')], max_length=3, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component', verbose_name='Комплектующее')),
            ],
            options={
                'verbose_name': 'Складская операция',
                'verbose_name_plural': 'Складские операции',
            },
        ),
    ]
